// Code generated by mockery v1.0.0. DO NOT EDIT.

package controller

import controller "github.com/spotahome/gontroller/controller"
import mock "github.com/stretchr/testify/mock"

// ListerWatcher is an autogenerated mock type for the ListerWatcher type
type ListerWatcher struct {
	mock.Mock
}

// List provides a mock function with given fields:
func (_m *ListerWatcher) List() ([]string, error) {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Watch provides a mock function with given fields:
func (_m *ListerWatcher) Watch() (<-chan controller.Event, error) {
	ret := _m.Called()

	var r0 <-chan controller.Event
	if rf, ok := ret.Get(0).(func() <-chan controller.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan controller.Event)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
